integrated_user_iplist_index:
  path: '/'
  methods: ['GET']
  defaults:
    _controller: 'Integrated\Bundle\UserBundle\Controller\IpListController::index'
integrated_user_iplist_new:
  path: '/new'
  defaults:
    _controller: 'Integrated\Bundle\UserBundle\Controller\IpListController::new'
integrated_user_iplist_edit:
  path: '/{id}'
  defaults:
    _controller: 'Integrated\Bundle\UserBundle\Controller\IpListController::edit'
integrated_user_iplist_delete:
  path: '/{id}/delete'
  defaults:
    _controller: 'Integrated\Bundle\UserBundle\Controller\IpListController::delete'
