<?php

namespace Integrated\Bundle\ImportBundle\Import\Converter;

use Symfony\Component\HttpFoundation\Session\Session;

class ExecuteImporter
{
    public static function configureExecutionEnvironment()
    {
        ini_set('max_execution_time', 3600);
        ini_set('memory_limit', '4G');
    }

    public static function handleSession()
    {
        $session = new Session();
        $session->save();
    }

    public static function getData($importDefinition, $doctrine, $importFile)
    {
        if ($importDefinition->getConnectionUrl() && $importDefinition->getConnectionQuery()) {
            return $doctrine->toArray($importDefinition);
        } else {
            return $importFile->toArray($importDefinition);
        }
    }

    public static function getImportType($importDefinition, $data, $importFile)
    {
        $file_content = file_get_contents($importFile->getFilePath($importDefinition));
        $is_wordpress_export = strpos(
                                   $file_content,
                                   'This is a WordPress eXtended RSS file generated by WordPress'
                               ) !== false
                               || strpos($file_content, 'xmlns:wp="http://wordpress.org/export/1.2/"') !== false
                               || strpos($file_content, 'wp-content') !== false;

        foreach ($data as $key => $value) {
            foreach ($value as $columnKey => $columnValue) {
                if (strpos($columnValue, 'wp-content') !== false) {
                    $is_wordpress_export = true;
                }
            }
            if ($key > 5) {
                break;
            }
        }

        $is_drupal_export = strpos($file_content, 'uuid: ') !== false;

        if ($is_wordpress_export) {
            $type = 'WordPress';
        } elseif ($is_drupal_export) {
            $type = 'Drupal';
        } else {
            $type = 'unknown';
        }

        return $type;
    }

    public static function initializeResult()
    {
        return [
            'done' => true,
            'messages' => [],
            'success' => [],
            'errors' => [],
        ];
    }

    public static function calculateRemainingTime($request, $newStart, $totalRowNumber)
    {
        $startTime = (int)$request->get('startTime', time());
        $duration = time() - $startTime;
        $remaining = ($duration / max(1, $newStart - 1)) * ($totalRowNumber - max(1, $newStart - 1));

        $elapsedMinutes = floor($duration / 60);
        $elapsedSeconds = $duration % 60;
        $elapsedStr = "{$elapsedMinutes}m {$elapsedSeconds}s elapsed and {$newStart} of {$totalRowNumber} records processed";

        if ($remaining >= 3600) {
            $remainingHours = floor($remaining / 3600);
            $remainingMinutes = floor(($remaining % 3600) / 60);
            $remainingStr = "{$remainingHours}h {$remainingMinutes}m remaining";
        } elseif ($remaining >= 60) {
            $remaining = round($remaining / 60);
            $remainingStr = "$remaining minutes remaining";
        } else {
            $remaining = round($remaining);
            $remainingStr = "$remaining seconds remaining";
        }

        $percentage = min(100, number_format((($newStart - 1) / $totalRowNumber) * 100, 2));
        $feedbackMsg = ($newStart - 1) >= $totalRowNumber ? 'Process completed.' : "Processing... $elapsedStr, $remainingStr";

        return [
            'percentage' => $percentage,
            'remaining' => $remainingStr,
            'elapsed' => $elapsedStr,
            'feedbackMsg' => $feedbackMsg,
            'startRow' => $newStart ?? null,  // This will return null if $startRow is not set
        ];
    }
}
