integrated_theme_scraper_index:
  path: '/scraper'
  methods: ['GET']
  defaults:
    _controller: 'Integrated\Bundle\ThemeBundle\Controller\ScraperController::index'
integrated_theme_scraper_new:
  path: '/scraper/new'
  defaults:
    _controller: 'Integrated\Bundle\ThemeBundle\Controller\ScraperController::new'
integrated_theme_scraper_edit:
  path: '/scraper/{id}'
  defaults:
    _controller: 'Integrated\Bundle\ThemeBundle\Controller\ScraperController::edit'
integrated_theme_scraper_delete:
  path: '/scraper/{id}/delete'
  defaults:
    _controller: 'Integrated\Bundle\ThemeBundle\Controller\ScraperController::delete'
