<?php

namespace Integrated\Bundle\FacebookBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class IntegratedFacebookBundle extends Bundle
{
    public function getContainerExtension()
    {
        return parent::getContainerExtension(); // TODO: Change the autogenerated stub
    }

}
